# Default values for guac.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## @section Global parameters
## @param imagePullSecrets[0].name Docker registry secret name for pulling images
imagePullSecrets:
  - name: imagepullsecret

## @section Guac
## @descriptionStart This section contains parameters for configuring the different GUAC components.
## @descriptionEnd
## @param guac.workingDir Working Directory for GUAC
## @param guac.ociCollector.name String Name of the OCI Collector component.
## @param guac.ociCollector.annotations.reloader.stakater.com/auto [string] Boolean for deploying [stakater/Reloader] (https://github.com/stakater/Reloader)
## @param guac.ociCollector.replicas Number of replicas for oci collector deployment
## @param guac.ociCollector.image.repository Path to the OCI Collector image
## @param guac.ociCollector.image.tag [nullable] Tag if using an image tag.  Optional
## @param guac.ociCollector.image.digest [string] Sha256 Image Digest.  It is strongly recommended to use this for verification.
## @param guac.ociCollector.image.pullPolicy ImagePullPolicy for kubernetes
## @param guac.ociCollector.image.command Command for the OCI Collector image.  It is not recommended to override this.
## @param guac.depsDevCollector.name String Name of the Deps.Dev Collector component.
## @param guac.depsDevCollector.annotations.reloader.stakater.com/auto [string] Boolean for deploying [stakater/Reloader] (https://github.com/stakater/Reloader)
## @param guac.depsDevCollector.replicas Number of replicas for depsdev collector deployment
## @param guac.depsDevCollector.image.repository Path to the Deps.Dev Collector image
## @param guac.depsDevCollector.image.tag [nullable] Tag if using an image tag.  Optional
## @param guac.depsDevCollector.image.digest [string] Sha256 Image Digest.  It is strongly recommended to use this for verification.
## @param guac.depsDevCollector.image.pullPolicy ImagePullPolicy for kubernetes
## @param guac.depsDevCollector.image.command Command for the Deps.Dev Collector image.  It is not recommended to override this.
## @param guac.osvCertifier.name String Name of the OSV Certifier component.
## @param guac.osvCertifier.annotations.reloader.stakater.com/auto [string] Boolean for deploying [stakater/Reloader] (https://github.com/stakater/Reloader)
## @param guac.osvCertifier.replicas Number of replicas for OSV Certifier deployment
## @param guac.osvCertifier.image.repository Path to the OSV Certifier Collector image
## @param guac.osvCertifier.image.tag [nullable] Tag if using an image tag.  Optional
## @param guac.osvCertifier.image.digest [string] Sha256 Image Digest.  It is strongly recommended to use this for verification.
## @param guac.osvCertifier.image.pullPolicy ImagePullPolicy for kubernetes
## @param guac.osvCertifier.image.command Command for the OSV Certifier Collector image.  It is not recommended to override this.
## @param guac.ingestor.name String Name of the ingestor component.
## @param guac.ingestor.annotations.reloader.stakater.com/auto [string] Boolean for deploying [stakater/Reloader] (https://github.com/stakater/Reloader)
## @param guac.ingestor.replicas Number of replicas for ingestor deployment
## @param guac.ingestor.image.repository Path to the Ingestor image
## @param guac.ingestor.image.tag [nullable] Tag if using an image tag.  Optional
## @param guac.ingestor.image.digest [string] Sha256 Image Digest.  It is strongly recommended to use this for verification.
## @param guac.ingestor.image.pullPolicy ImagePullPolicy for kubernetes
## @param guac.ingestor.image.command Command for the ingestor image.  It is not recommended to override this.
## @param guac.collectSub.name String Name of the Collector Sub component.
## @param guac.collectSub.annotations.reloader.stakater.com/auto [string] Boolean for deploying [stakater/Reloader] (https://github.com/stakater/Reloader)
## @param guac.collectSub.replicas Number of replicas for Collector Sub deployment
## @param guac.collectSub.image.repository Path to the Collector Sub image
## @param guac.collectSub.image.tag [nullable] Tag if using an image tag.  Optional
## @param guac.collectSub.image.digest [string] Sha256 Image Digest.  It is strongly recommended to use this for verification.
## @param guac.collectSub.image.pullPolicy ImagePullPolicy for kubernetes
## @param guac.collectSub.image.command Command for the Collector Sub image.  It is not recommended to override this.
## @param guac.collectSub.ports[0].protocol Protocol used at Collector Sub
## @param guac.collectSub.ports[0].port Port the Collector Sub service listens on
## @param guac.collectSub.ports[0].targetPort Port the Collector Sub container listens on
## @param guac.graphqlServer.name String Name of the GraphQL Server component.
## @param guac.graphqlServer.annotations.reloader.stakater.com/auto [string] Boolean for deploying [stakater/Reloader] (https://github.com/stakater/Reloader)
## @param guac.graphqlServer.replicas Number of replicas for GraphQL Server deployment
## @param guac.graphqlServer.image.repository Path to the GraphQL Server image
## @param guac.graphqlServer.image.tag [nullable] Tag if using an image tag.  Optional
## @param guac.graphqlServer.image.digest [string] Sha256 Image Digest.  It is strongly recommended to use this for verification.
## @param guac.graphqlServer.image.pullPolicy ImagePullPolicy for kubernetes
## @param guac.graphqlServer.image.command Command for the GraphQL Server image.  It is not recommended to override this.
## @param guac.graphqlServer.ports[0].protocol Protocol used at the the GraphQL Server
## @param guac.graphqlServer.ports[0].port Port the GraphQL Server service listens on
## @param guac.graphqlServer.ports[0].targetPort Port the GraphQL Server container listens on
## @param guac.graphqlServer.backend Which backend to use - inmem or neo4j. If neo4j, neo4j.enabled must be set to true.
## @param guac.graphqlServer.debug Enable debug mode for graphql server; also enable the UI
## @param guac.observability.deployServiceMonitor Boolean Deploy the service monitor for observability
## @param guac.sampleData.ingest Boolean - set to true to ingest sample data after deployment
## @param guac.sampleData.jobName Name of the sample data ingest job
guac:
  workingDir: /workspace
  # workingDir: /guac

  ociCollector:
    name: oci-collector
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    image:
      repository: ghcr.io/kusaridev/local-organic-guac
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: "sha256:b11d8361368409333c6ed8c0a94dc395814a23828d15cfe54a3e45e973fb3b99"
      pullPolicy: IfNotPresent
      command: ['sh', '-c', '/cnb/process/collector image --use-csub']

  depsDevCollector:
    name: depsdev-collector
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    image:
      repository: ghcr.io/kusaridev/local-organic-guac
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: "sha256:b11d8361368409333c6ed8c0a94dc395814a23828d15cfe54a3e45e973fb3b99"
      pullPolicy: IfNotPresent
      command: ['sh', '-c', '/cnb/process/collector deps_dev --use-csub']

  osvCertifier:
    name: osv-certifier
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    image:
      repository: ghcr.io/kusaridev/local-organic-guac
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: "sha256:b11d8361368409333c6ed8c0a94dc395814a23828d15cfe54a3e45e973fb3b99"
      pullPolicy: IfNotPresent
      command: ['sh', '-c', '/cnb/process/guacone osv --poll --interval 5']

  ingestor:
    name: ingestor
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    image:
      repository: ghcr.io/kusaridev/local-organic-guac
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: "sha256:b11d8361368409333c6ed8c0a94dc395814a23828d15cfe54a3e45e973fb3b99"
      pullPolicy: IfNotPresent
      command: ['sh', '-c', '/cnb/process/ingest ingest']

  collectSub:
    name: collectsub
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    image:
      repository: ghcr.io/kusaridev/local-organic-guac
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: "sha256:b11d8361368409333c6ed8c0a94dc395814a23828d15cfe54a3e45e973fb3b99"
      pullPolicy: IfNotPresent
      command: ['sh', '-c', '/cnb/process/guacone csub-server']
    ports:
      - protocol: TCP
        port: 2782
        targetPort: 2782

  graphqlServer:
    name: graphql-server
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    image:
      repository: ghcr.io/kusaridev/local-organic-guac
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: "sha256:b11d8361368409333c6ed8c0a94dc395814a23828d15cfe54a3e45e973fb3b99"
      pullPolicy: IfNotPresent
      command: ['sh', '-c', '/cnb/process/guacone gql-server']
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    backend: inmem
    debug: false

  observability:
    deployServiceMonitor: false

  sampleData:
    ingest: true
    jobName: ingest-guac-data

## @section neo4j
## @descriptionStart This is the configuration for neo4j if being used.  This is a subchart.  See full documentation [here](https://neo4j.com/labs/neo4j-helm/1.0.0/).
## @descriptionEnd
## @param neo4j.enabled If false, neo4j will not be installed
## @param neo4j.neo4j.name Name of the neo4j instance
## @param neo4j.neo4j.password Initial password for neo4j instance
## @param neo4j.neo4j.edition Type of instance being used.  Example "community" or "enterprise"
## @param neo4j.neo4j.labels.release Label for release.  This is used as part of monitoring
## @param neo4j.neo4j.labels.app.kubernetes.io/part-of Label to associate neo4j as part of GUAC for monitoring purposes.
## @param neo4j.neo4j.resources.cpu CPU allocation for neo4j
## @param neo4j.neo4j.resources.memory Memory allocation for neo4j
## @param neo4j.services.neo4j.spec.type Kubernetes service type for neo4j service
## @param neo4j.config.server.directories.plugins Required for APOC plugin.  See [here](https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/)
## @param neo4j.config.dbms.security.procedures.unrestricted Required for APOC plugin.  See [here](https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/)
## @param neo4j.config.server.config.strict_validation.enabled Required for APOC plugin.  See [here](https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/)
## @param neo4j.config.dbms.security.procedures.allowlist Required for APOC plugin.  See [here](https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/)
## @param neo4j.config.server.metrics.enabled Boolean to turn on server metrics.
## @param neo4j.config.server.metrics.prometheus.enabled Boolean to turn on prometheus
## @param neo4j.config.server.metrics.prometheus.endpoint Endpoint location for prometheus
## @param neo4j.jvm.additionalJvmArguments JVM Arguments for the neo4j server.
## @param neo4j.volumes.data.mode Data mode for neo4j volume mount.
## @param neo4j.volumes.data.dynamic.storageClassName Storage class for neo4j volume mount.
## @param neo4j.volumes.data.dynamic.requests.storage Size of neo4j volume mount.
neo4j:
  enabled: false

  neo4j:
    name: guac-neo4j
    # The chart will generate a secret if password is not specified
    password: "s3cr3ts3cr3t"

    edition: "community"
    # edition: "enterprise"
    # acceptLicenseAgreement: "yes"

    labels:
      release: monitoring
      app.kubernetes.io/part-of: "guac"

    resources:
      # cpu: "1"
      cpu: "1000m"
      memory: "4Gi"

  services:
    neo4j:
      spec:
        type: ClusterIP

  config:

    server.directories.plugins: "/var/lib/neo4j/labs"
    dbms.security.procedures.unrestricted: "apoc.*"
    server.config.strict_validation.enabled: "false"
    dbms.security.procedures.allowlist: "gds.*,apoc.*"

    server.metrics.enabled: "true"
    server.metrics.prometheus.enabled: "true"
    server.metrics.prometheus.endpoint: "0.0.0.0:2004"

  # Jvm configuration for Neo4j
  jvm:
    additionalJvmArguments:
    - "-XX:+HeapDumpOnOutOfMemoryError"
    - "-XX:HeapDumpPath=/logs/neo4j.hprof"

  # apoc_config:
  #   apoc.trigger.enabled: "true"
  #   apoc.jdbc.neo4j.url: "jdbc:foo:bar"
  #   apoc.import.file.enabled: "true"

  volumes:
    data:
      mode: "dynamic"
      dynamic:
       # gp2 is a general-purpose SSD volume
      #  storageClassName: gp2
        storageClassName: standard
        requests:
          storage: 100Gi
      # accessModes:
      #   - ReadWriteOnce


## @section neo4j
## @descriptionStart This is the configuration for nats.  This is a subchart.  See full documentation [here](https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts).
## @descriptionEnd
## @param nats.nats.jetstream.enabled Boolean for enabling JetStream.
## @param nats.nats.limits.maxPayload Max Payload size for nats
## @param nats.nats.statefulSetPodLabels.app.kubernetes.io/part-of Label to associate nats with GUAC for monitoring purposes
## @param nats.natsbox.additionalLabels.app.kubernetes.io/part-of Label to associate natsbox with GUAC for monitoring purposes
## @param nats.natsbox.podLabels.app.kubernetes.io/part-of Label to associate natsbox with GUAC for monitoring purposes
## @param nats.exporter.enabled Boolean to enable data collection
## @param nats.exporter.serviceMonitor.enabled Boolean to enable nats service monitor
## @param nats.exporter.serviceMonitor.namespace nats service monitor namespace - this is for monitoring purposes and is used by Prometheus
## @param nats.exporter.serviceMonitor.labels.release Label to associate nats service monitor with GUAC for monitoring purposes
nats:
  nats:
    jetstream:
      enabled: true
    limits:
      # change max payload from default 1MB to 64MB
      maxPayload: 64MB
    statefulSetPodLabels:
      app.kubernetes.io/part-of: "guac"

  natsbox:
    additionalLabels:
      app.kubernetes.io/part-of: "guac"
    podLabels:
      app.kubernetes.io/part-of: "guac"

  exporter:
    enabled: true
    serviceMonitor:
      enabled: false
      ## Specify the namespace where Prometheus Operator is running
      namespace: monitoring
      labels:
        release: monitoring
