# TO-DO: generate service based on values.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.guac.graphqlServer.name }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
spec:
  selector:
    {{- include "guac.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
  ports:
    # TO-DO: generate this from the list of ports
    - protocol: TCP
      port: 8080
      targetPort: 8080