apiVersion: v1
kind: ConfigMap
metadata:
  name: guac-cm
data:
  guac.yaml: |
    # neo4j
    gdbuser: neo4j
    gdbpass: s3cr3ts3cr3t
    gdbaddr: neo4j://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:7687
    realm: neo4j

    # nats
    natsaddr: nats://{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222

    # collect-sub
    csub-addr: {{ .Values.guac.collectSub.name }}.{{ .Release.Namespace }}.svc.cluster.local:2782
    csub-listen-port: 2782

    # graphql
    gql-backend: neo4j
    gql-port: 8080
    gql-debug: false
    gql-endpoint: http://{{ .Values.guac.graphqlServer.name }}.{{ .Release.Namespace }}.svc.cluster.local:8080/query