apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.guac.restApi.name }}
{{- if .Values.guac.restApi.annotations }}
  annotations:
{{ toYaml .Values.guac.restApi.serviceAccount.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.restApi.name }}
    app.kubernetes.io/component: {{ .Values.guac.restApi.name }}