# Copyright Kusari, Inc. and contributors
# Licensed under the MIT license. See LICENSE file in the project root for details.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guac-cm
data:
  guac.yaml: |

    # nats
    natsaddr: nats://{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222

    # collect-sub
{{- with (index .Values.guac.collectSub.ports 0) }}
    csub-addr: {{ $.Values.guac.collectSub.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .targetPort }}
    csub-listen-port: {{ .targetPort }}
{{- end }}

    # graphql-server
{{- with (index .Values.guac.graphqlServer.ports 0) }}
    gql-backend: {{ $.Values.guac.graphqlServer.backend }}
    gql-debug: {{ $.Values.guac.graphqlServer.debug }}
    gql-port: {{ .targetPort }}
    gql-endpoint: http://{{ $.Values.guac.graphqlServer.name }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .targetPort }}/query
{{- end }}