{{- if .Values.guac.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}

{{- if .Values.guac.ingress.annotations }}
  annotations:
{{ toYaml .Values.guac.ingress.annotations | indent 4 }}
{{- end }}

  labels:
{{- include "guac.labels" . | nindent 4 }}
{{- range $key, $value := .Values.guac.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
{{- end }}

spec:
  {{- if .Values.guac.ingress.ingressClassName }}
  ingressClassName: {{ .Values.guac.ingress.ingressClassName }}
  {{- end }}
  rules:
    {{ if .Values.guac.ingress.webuiHostname }}
    - host: {{ .Values.guac.ingress.webuiHostname }}
      http: &http
        paths:
          - path: /playground
            pathType: Prefix
            backend:
              service:
                name: graphql-server
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visualizer
                port:
                  number: 3000
    {{ end }}
    {{ if .Values.guac.ingress.apiHostname }}
    - host: {{ .Values.guac.ingress.apiHostname }}
      http:
        paths:
    {{ end }}
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: graphql-server
                port:
                  number: 8080
{{- end -}}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: alb-oidc-secret-read 
rules:
  - apiGroups:
       - ""
    resourceNames:
      - alb-oidc-secret
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: alb-oidc-secret-read 
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: alb-oidc-secret-read
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller
    namespace: kube-system