name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
           version: 'v3.11.2'

      - name: Add Helm repos
        run: |
          helm repo add neo4j https://helm.neo4j.com/neo4j
          helm repo add nats https://nats-io.github.io/k8s/helm/charts

      # - name: Prepare GPG key
      #   run: |
      #     gpg_dir=.cr-gpg
      #     mkdir "$gpg_dir"
      #     keyring="$gpg_dir/secring.gpg"
      #     base64 -d <<< "$GPG_KEYRING_BASE64" > "$keyring"
      #     passphrase_file="$gpg_dir/passphrase"
      #     echo "$GPG_PASSPHRASE" > "$passphrase_file"
      #     echo "CR_PASSPHRASE_FILE=$passphrase_file" >> "$GITHUB_ENV"
      #     echo "CR_KEYRING=$keyring" >> "$GITHUB_ENV"
      #   env:
      #     GPG_KEYRING_BASE64: "${{ secrets.GPG_KEYRING_BASE64 }}"
      #     GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"

      - name: Set up GPG Keys
        run: |
          cat <(echo -e "${{ secrets.GPG_KEYRING_BASE64 }}") | base64 -d | gpg --import --batch
          gpg --export-secret-keys > /home/runner/.gnupg/keyring.gpg

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SIGN: "true"
          # GPG_KEY_NAME is set at key creation time and is used to identify the key in the keyring here
          CR_KEY: "${{ secrets.GPG_KEY_NAME }}"
          CR_KEYRING: "/home/runner/.gnupg/keyring.gpg"
