name:  Helm Tests

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run helm unittest
        run: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest charts/guac -3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
           version: 'v3.11.2' 

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Add Helm repos
        run: |
          helm repo add neo4j https://helm.neo4j.com/neo4j
          helm repo add nats https://nats-io.github.io/k8s/helm/charts

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          echo "::set-output name=changed::true"
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --all --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        # if: steps.list-changed.outputs.changed == 'true'

      - uses: azure/k8s-set-context@v3
        with:
           method: kubeconfig
          #  kubeconfig: <your kubeconfig>
           context: kind-chart-testing

      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
           namespace: 'guac-ct'
           secret-name: 'imagepullsecret'
           container-registry-url: 'ghcr.io'
           container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
           container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        id: create-secret

      - uses: actions-hub/kubectl@master
        # env:
        #   KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: 'patch serviceaccount default -p "{\"imagePullSecrets\": [{\"name\": \"imagepullsecret\"}]}" -n guac-ct'

      - name: Run chart-testing (install)
        run: ct install --all --namespace guac-ct --helm-extra-args --timeout=600s
        # if: steps.list-changed.outputs.changed == 'true'
